name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Node ${{matrix.node_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [16, 18, 20]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          packageManager: 'pnpm'
          nodeVersion: ${{matrix.node_version}}

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Integrity check
        run: npx bob check